정수빈/Programmers/Level2/n^2 배열 자르기.py, 정수빈/Programmers/Level2/올바른 괄호.py
https://school.programmers.co.kr/learn/courses/30/lessons/12909 (이건 고득점키트에 있던거더라구요 ㅠ 모든 코테문제로 봤는디) 
https://school.programmers.co.kr/learn/courses/30/lessons/87390
=> [2024-11-01] 프로그래머스 레벨2

장세훈/LeetCode/ReverseString.java, 장세훈/LeetCode/ValidPalindrome.java
- https://leetcode.com/problems/reverse-string/
- https://leetcode.com/problems/valid-palindrome/description/
-
=> [2024-11-02] 장세훈 leet code easy

장세훈/Programmers/Level1/가장_가까운_같은_글자.java, 장세훈/Programmers/Level1/동영상_재생기.java
- https://school.programmers.co.kr/learn/courses/30/lessons/340213
- https://school.programmers.co.kr/learn/courses/30/lessons/142086
- level1부터..
=> [2024-11-01] 장세훈

장세훈/LeetCode/easy/ArrayPartition.java, 장세훈/LeetCode/medium/ProductOfArrayExceptSelf.java
- https://leetcode.com/problems/array-partition/
- https://leetcode.com/problems/product-of-array-except-self/description/
-238. Product of Array Except Self 문제는 못풀어서 해답을 봤는데, 어떻게 이런 풀이를 도출하는지 신기하네요 
- leetcode로 문제를 풀면 속도와 메모리를 다른 사람 풀이를 비교해주는데요, 모범 답안을 제출했음에도 메모리 효율이 낮길래 이상하다 해서 다른 사람 코드를 봤더니 가비지 컬렉터를 호출하고 있네요. ㄷㄷㅋㅋ
=> 2024-11-08-sh

정수빈/LeetCode/easy/can-place-flowers.py, 정수빈/LeetCode/easy/greatest-common-divisor-of-strings.py, 정수빈/LeetCode/easy/is-subsequence.py, 정수빈/LeetCode/easy/kids-with-the-greatest-number-of-candies.py, 정수빈/LeetCode/easy/maximum-average-subarray-i.py, 정수빈/LeetCode/easy/move-zeroes.py, 정수빈/LeetCode/easy/reverse-vowels-of-a-string.py, 정수빈/LeetCode/medium/container-with-most-water.py, 정수빈/LeetCode/medium/daily-temperatures.py, 정수빈/LeetCode/medium/increasing-triplet-subsequence.py, 정수빈/LeetCode/medium/online-stock-span.py, 정수빈/LeetCode/medium/reverse-words-in-a-string.py, 정수빈/LeetCode/medium/string-compression.py
=> 주말 포함해서 문제 올립니당

장세훈/LeetCode/easy/BestTimeToBuyAndSellStock.java, 장세훈/Programmers/Level2/주식가격.java
- https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/
- https://school.programmers.co.kr/learn/courses/30/lessons/42584?language=java
-
=> 2024-11-11-sh

장세훈/LeetCode/easy/MergeTwoSortedLists.java, 장세훈/LeetCode/easy/PalindromeLinkedList.java
- https://leetcode.com/problems/merge-two-sorted-lists/description/
- https://leetcode.com/problems/palindrome-linked-list/description/
-  아 저는  지저분하고 어렵게 푸는데, 다른 사람 코드보면 참 간결하네요 ㅋㅋ
=> 2024-11-12-sh

오우영/Programmers/Level1/가장가까운같은글자.js, 오우영/Programmers/Level1/크기가작은부분문자열.js
- [가장가까운같은글자](https://school.programmers.co.kr/learn/courses/30/lessons/142086)
- [크기가작은부분문자열](https://school.programmers.co.kr/learn/courses/30/lessons/147355)
-
=> 가장가까운같은글자, 크기가작은부분문자열

장세훈/LeetCode/easy/ReverseLinkedList.java, 장세훈/LeetCode/medium/AddTwoNumbers.java
- https://leetcode.com/problems/add-two-numbers/description/
- https://leetcode.com/problems/reverse-linked-list/description/
-
=> 2024-11-13-sh

오우영/Programmers/Level2/뒤에있는큰수찾기.js, 오우영/Programmers/Level2/숫자변환하기.js
- [숫자 변환하기](https://school.programmers.co.kr/learn/courses/30/lessons/154538)
- [뒤에 있는 큰수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/154539)
-
=> 뒤에있는큰수찾기, 숫자변환하기

정수빈/LeetCode/easy/binary-tree-inorder-traversal.py, 정수빈/LeetCode/easy/guess-number-higher-or-lower.py, 정수빈/LeetCode/easy/k-pair.py, 정수빈/LeetCode/easy/largest-local-values-in-a-matrix.py, 정수빈/LeetCode/easy/maximum-depth-of-binary-tree.py, 정수빈/LeetCode/easy/number-of-recent-calls.py, 정수빈/LeetCode/easy/reshape-the-matrix.py, 정수빈/LeetCode/easy/reverse-linked-list.py, 정수빈/LeetCode/easy/same-tree.py, 정수빈/LeetCode/easy/search-in-a-binary-search-tree.py, 정수빈/LeetCode/easy/transpose-matrix.py, 정수빈/LeetCode/medium/asteroid-collision.py, 정수빈/LeetCode/medium/count-good-nodes-in-binary-tree.py, 정수빈/LeetCode/medium/keys-and-rooms.py, 정수빈/LeetCode/medium/kth-largest-element-in-an-array.py, 정수빈/LeetCode/medium/longest-zigzag-path-in-a-binary-tree.py, 정수빈/LeetCode/medium/maximum-number-of-vowels-in-a-substring-of-given-length.py, 정수빈/LeetCode/medium/number-of-provinces.py, 정수빈/LeetCode/medium/removing-stars-from-a-string.py, 정수빈/LeetCode/medium/successful-pairs-of-spells-and-potions.py, 정수빈/LeetCode/medium/validate-binary-search-tree.py, 정수빈/Programmers/test2.py, 정수빈/Programmers/test3.py, 정수빈/연습/a.py, 정수빈/연습/heap.py, 정수빈/연습/merge_sort.py
- 
- 아니 너무 폭주하듯이 풀어서 설명을 거의 못적었네요 ㅠㅠ 오늘까지만 이렇게 하고 내일부터는 성실하게 업로드하겠습니다
=> 어제 오늘 푼 거 올립니다

장세훈/LeetCode/medium/OddEvenLinkedList.java, 장세훈/LeetCode/medium/SwapNodesInPairs.java
- https://leetcode.com/problems/odd-even-linked-list/
-  https://leetcode.com/problems/swap-nodes-in-pairs/description/
-
=> 2024-11-14-sh

정수빈/LeetCode/easy/find-the-difference-of-two-arrays.py, 정수빈/LeetCode/medium/group-anagrams.py, 정수빈/LeetCode/medium/unique-paths.py, 정수빈/LeetCode/medium/valid-sudoku.py, 정수빈/LeetCode/top_interview/best-time-to-buy-and-sell-stock.py, 정수빈/LeetCode/top_interview/majority-element.py, 정수빈/LeetCode/top_interview/merge-sorted-array.py, 정수빈/LeetCode/top_interview/remove-duplicates-from-sorted-array-ii.py, 정수빈/LeetCode/top_interview/remove-duplicates-from-sorted-array.py, 정수빈/LeetCode/top_interview/remove-element.py, 정수빈/LeetCode/top_interview/rotate-array.py
- https://leetcode.com/problems/group-anagrams
- https://leetcode.com/problems/best-time-to-buy-and-sell-stock
- https://leetcode.com/problems/majority-element
- https://leetcode.com/problems/merge-sorted-array
- https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/
- https://leetcode.com/problems/remove-duplicates-from-sorted-array
- https://leetcode.com/problems/remove-element
- https://leetcode.com/problems/rotate-array
- 어제분 포함해서 pr 올립니다!!
=> 2024 11 15 수빈

장세훈/LeetCode/easy/JewelsAndStones.java, 장세훈/LeetCode/medium/number of islands, 장세훈/Programmers/Level1/완주하지_못한_선수.java
- https://leetcode.com/problems/jewels-and-stones/description/
- https://leetcode.com/problems/number-of-islands/description/
- https://school.programmers.co.kr/learn/courses/30/lessons/42576
-
=> 2024-11-19-sh

장세훈/LeetCode/medium/CombinationSum.java, 장세훈/LeetCode/medium/Combinations.java
- https://leetcode.com/problems/combination-sum/description/
-  https://leetcode.com/problems/combinations/description/
-
=> 22024-11-24-sh

정수빈/LeetCode/easy/palindrome-number.py, 정수빈/LeetCode/easy/ransom-note.py, 정수빈/LeetCode/easy/summary-ranges.py, 정수빈/LeetCode/medium/longest-palindromic-substring.py, 정수빈/LeetCode/medium/longest-substring-without-repeating-characters.py
=> 2024-11-23 리트코드

정수빈/LeetCode/easy/n-th-tribonacci-number.py, 정수빈/LeetCode/easy/valid-parentheses.py, 정수빈/LeetCode/hard/median-of-two-sorted-arrays.py, 정수빈/LeetCode/medium/combination-sum.py, 정수빈/LeetCode/medium/combinations.py, 정수빈/LeetCode/medium/generate-parentheses.py, 정수빈/LeetCode/medium/letter-combinations-of-a-phone-number.py, 정수빈/LeetCode/medium/merge-intervals.py, 정수빈/LeetCode/medium/permutations.py
=> 2024-11-24 리트코드

장세훈/LeetCode/hard/ReconstructItinerary.java, 장세훈/LeetCode/medium/Subsets.java
- https://leetcode.com/problems/reconstruct-itinerary/description/
- https://leetcode.com/problems/subsets/description/
-
=> 2024-11-25-sh

정수빈/LeetCode/medium/binary-tree-vertical-order-traversal.py, 정수빈/Programmers/Level2/게임맵최단거리.py, 정수빈/Programmers/Level2/타겟넘버.py, 정수빈/Programmers/Level3/네트워크.py
=> 2024-11-25 리트코드

장세훈/LeetCode/medium/CourseSchedule.java, 장세훈/Programmers/Level2/[1차]캐시.java
- https://leetcode.com/problems/course-schedule/description/
- https://school.programmers.co.kr/learn/courses/30/lessons/17680
-
=> 2024-11-26-sh

장세훈/LeetCode/medium/NetworkDelayTime.java, 장세훈/Programmers/Level2/배달.java
- https://leetcode.com/problems/network-delay-time/description/
- https://school.programmers.co.kr/learn/courses/30/lessons/12978
-
=> 2024-11-27-sh

오우영/Programmers/Level2/귤고르기.js, 오우영/Programmers/Level2/연속된부분수열의합.js
- [귤고르기](https://school.programmers.co.kr/learn/courses/30/lessons/138476)
- [연속된부분수열의합](https://school.programmers.co.kr/learn/courses/30/lessons/178870)
-
=> 귤고르기, 연속된부분수열의합

장세훈/Programmers/Level2/게임맵최단거리.java, 장세훈/Programmers/Level2/타켓넘버.java
- https://school.programmers.co.kr/learn/courses/30/lessons/1844
- https://school.programmers.co.kr/learn/courses/30/lessons/43165?language=java
-
=> 2024-11-28-sh

정수빈/LeetCode/easy/average-of-levels-in-binary-tree.py, 정수빈/LeetCode/medium/binary-tree-level-order-traversal.py, 정수빈/LeetCode/medium/binary-tree-right-side-view.py, 정수빈/LeetCode/medium/binary-tree-zigzag-level-order-traversal.py, 정수빈/LeetCode/medium/number-of-islands.py, 정수빈/LeetCode/medium/validate-binary-search-tree.py
=> 2024-11-26 리트코드

정수빈/LeetCode/easy/is-subsequenc.py, 정수빈/LeetCode/easy/isomorphic-strings.py
-
- 오늘은 쉬어가는 의미로 리트코드 easy로 했습니다 ㅋㅋㅋ
=> 2024-11-27 리트코드

정수빈/LeetCode/easy/factorial-trailing-zeroes.py, 정수빈/LeetCode/easy/length-of-last-word.py, 정수빈/LeetCode/easy/longest-common-prefix.py, 정수빈/LeetCode/easy/plus-one.py, 정수빈/LeetCode/easy/sqrtx.py, 정수빈/LeetCode/easy/valid-anagram.py, 정수빈/LeetCode/easy/word-pattern.py, 정수빈/LeetCode/medium/h-index.py, 정수빈/LeetCode/medium/integer-to-roman.py, 정수빈/LeetCode/medium/powx-n.py
=> 2024-11-28 리트코드

정수빈/LeetCode/easy/find-the-index-of-the-first-occurrence-in-a-string.py, 정수빈/LeetCode/medium/insert-delete-getrandom-o1.py, 정수빈/LeetCode/medium/product-of-array-except-self.py, 정수빈/LeetCode/medium/zigzag-conversion.py
=> 2024-11-29 리트코드

정수빈/LeetCode/hard/integer-to-english-words.py, 정수빈/LeetCode/medium/spiral-matrix.py
- https://leetcode.com/problems/integer-to-english-words/
- https://leetcode.com/problems/spiral-matrix/
- leetcode 빈도순으로 정렬해서 hard하나 
- top interview 150에서 medium 하나
=> 2024-12-02 리트코드

오우영/Programmers/Level2/n^2배열자르기.js, 오우영/Programmers/Level2/연속부분수열합의개수.js
- [연속 부분 수열 합의 개수](https://school.programmers.co.kr/learn/courses/30/lessons/131701)
- [n^2 배열 자르기](https://school.programmers.co.kr/learn/courses/30/lessons/87390)
-
=> 2024-11-29 n^2배열자르기, 연속부분수열합의개수

정수빈/LeetCode/easy/linked-list-cycle.py, 정수빈/LeetCode/medium/surrounded-regions.py
- https://leetcode.com/problems/linked-list-cycle/?envType=study-plan-v2&envId=top-interview-150
- https://leetcode.com/problems/surrounded-regions/?envType=study-plan-v2&envId=top-interview-150
-
=> 2024-12-04 리트코드

정수빈/LeetCode/easy/contains-duplicate-ii.py, 정수빈/LeetCode/easy/happy-number.py, 정수빈/LeetCode/easy/invert-binary-tree.py, 정수빈/LeetCode/easy/maximum-depth-of-binary-tree_2.py, 정수빈/LeetCode/easy/path-sum.py, 정수빈/LeetCode/easy/symmetric-tree.py, 정수빈/LeetCode/medium/sum-root-to-leaf-numbers.py
전부 top-interview-150, 대부분 easy
- https://leetcode.com/problems/contains-duplicate-ii
- https://leetcode.com/problems/happy-number/?envType=study-plan-v2&envId=top-interview-150
- https://leetcode.com/problems/invert-binary-tree/?envType=study-plan-v2&envId=top-interview-150
- https://leetcode.com/problems/maximum-depth-of-binary-tree/?envType=study-plan-v2&envId=top-interview-150
- https://leetcode.com/problems/path-sum/?envType=study-plan-v2&envId=top-interview-150
- https://leetcode.com/problems/sum-root-to-leaf-numbers/?envType=study-plan-v2&envId=top-interview-150
- 미디엄, 하드 잘 풀고 싶습니다ㅏㅏㅏㅏ
=> 2024-12-03 두번째 리트코드

장세훈/LeetCode/easy/MergeTwoBinaryTrees.java, 장세훈/LeetCode/medium/SpiralMatrix.java
- https://leetcode.com/problems/merge-two-binary-trees/description/
- https://leetcode.com/problems/spiral-matrix/
-
=> 2024-12-03-sh

곽경진/Programmers/Level2/k진수에서 소수 개수 구하기.java, 곽경진/Programmers/Level2/이진_변환_반복하기.java
[k진수에서 소수 개수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/92335)
[이진 변환 반복하기](https://school.programmers.co.kr/learn/courses/30/lessons/70129)
-
=> 2024-12-04

장세훈/LeetCode/easy/BalancedBinaryTree.java, 장세훈/LeetCode/easy/LinkedListCycle.java
- https://leetcode.com/problems/balanced-binary-tree/description/
- https://leetcode.com/problems/linked-list-cycle/description/?envType=study-plan-v2&envId=top-interview-150
- 문제를 잘 못 이해해서 뻘짓했었네요. 아 영어 공부도 해야되나.
=> 2024-12-04-sh

오우영/Programmers/Level2/k진수에서소수개수구하기.js, 오우영/Programmers/Level2/롤케이크자르기.js
- [k진수에서소수개수구하기](https://school.programmers.co.kr/learn/courses/30/lessons/92335)
- [롤케이크자르기](https://school.programmers.co.kr/learn/courses/30/lessons/132265)
-
=> 2024-12-04 롤케이크자르기, k진수에서소수개수구하기

곽경진/Programmers/Level2/다음_큰_숫자.java, 곽경진/Programmers/Level2/문자열_내림차순_배치하기.java
- [다음 큰 숫자](https://school.programmers.co.kr/learn/courses/30/lessons/12911)
- [문자열 내림차순 배치하기](https://school.programmers.co.kr/learn/courses/30/lessons/12917)
-
=> 20124-12-06

장세훈/LeetCode/easy/ConvertSortedArrayToBinarySearchTree.java, 장세훈/LeetCode/easy/RangeSumBST.java
- https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/description/
- https://leetcode.com/problems/range-sum-of-bst/description/
-
=> 2024-12-06-sh

정수빈/LeetCode/samsung/binary-search.py, 정수빈/LeetCode/samsung/lru-cache.py
- https://leetcode.com/problems/binary-search/?envType=company&envId=samsung&favoriteSlug=samsung-all
- https://leetcode.com/problems/lru-cache/?envType=company&envId=samsung&favoriteSlug=samsung-three-months
- 리트코드에는 빅테크 중심으로 회사별로 유형을 묶어주는데, 그중에 삼성도 있더라구요
=> 2024-12-07 리트코드 삼성 문제 

정수빈/LeetCode/medium/string-to-integer-ato.py, 정수빈/LeetCode/samsung/largest-submatrix-with-rearrangements.py
- https://leetcode.com/problems/largest-submatrix-with-rearrangements/?envType=company&envId=samsung&favoriteSlug=samsung-all (리트코드 삼성문제)
- https://leetcode.com/problems/string-to-integer-atoi/ (빈도수 정렬)
-
=> 2024-12-06 리트코드

장세훈/LeetCode/easy/MinimumDistanceBetweenBSTNodes.java, 장세훈/Programmers/Level3/이중우선순위큐.java
- https://leetcode.com/problems/minimum-distance-between-bst-nodes/description/
- https://school.programmers.co.kr/learn/courses/30/lessons/42628
-
=> 2024-12-09-sh

곽경진/Programmers/Level2/피보나치의_수.java, 곽경진/Programmers/Level3/정수_삼각형.java
- [피보나치의_수](https://school.programmers.co.kr/learn/courses/30/lessons/12945)
- [정수_삼각형](https://school.programmers.co.kr/learn/courses/30/lessons/43105)
-
=> 2024-12-09-Kj

정수빈/LeetCode/easy/count-negative-numbers-in-a-sorted-matrix.py, 정수빈/LeetCode/easy/find-smallest-letter-greater-than-target.py, 정수빈/LeetCode/samsung/faulty-keyboard.py
=> 2024-12-09 리트코드

곽경진/Programmers/Level2/올바른_괄호.java, 곽경진/Programmers/Level2/짝지어_제거하기.java
- [올바른_괄호](https://school.programmers.co.kr/learn/courses/30/lessons/12909)
- [짝지어_제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/12973)
- 쉬운 문제가 얼마 안남았다...
=> 2024-12-10

오우영/Programmers/Level2/괄호회전하기.js, 오우영/Programmers/Level2/모음사전.js
- [괄호회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)
- [모음사전](https://school.programmers.co.kr/learn/courses/30/lessons/84512)
-
=> 2024-12-05 괄호회전하기, 모음사전

장세훈/LeetCode/easy/BinarySearch.java, 장세훈/LeetCode/medium/TwoSumII.java
- https://leetcode.com/problems/binary-search/submissions/1476054164/
- https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/submissions/1476143516/
-
=> 2024-12-11-sh

장세훈/LeetCode/easy/HammingDistance.java, 장세훈/LeetCode/easy/SingleNumber.java
- https://leetcode.com/problems/hamming-distance/description/
- https://leetcode.com/problems/single-number/description/
-
=> 2024-12-13-sh

장세훈/LeetCode/medium/SearchA2DMatrixII.java, 장세훈/Programmers/Level3/입국심사.java
- https://leetcode.com/problems/search-a-2d-matrix-ii/
-  https://school.programmers.co.kr/learn/courses/30/lessons/43238?language=java
-
=> 2024-12-12-sh

정수빈/LeetCode/easy/climbing-stairs.py, 정수빈/LeetCode/easy/fibonacci-number.py, 정수빈/LeetCode/medium/find-first-and-last-position-of-element-in-sorted-array.py
=> 2024-12-10 리트코드

정수빈/LeetCode/easy/find-the-highest-altitude.py, 정수빈/LeetCode/easy/min-cost-climbing-stairs.py, 정수빈/LeetCode/medium/determine-if-two-strings-are-close.py, 정수빈/LeetCode/medium/equal-row-and-column-pairs.py
- https://leetcode.com/problems/find-the-highest-altitude/?envType=study-plan-v2&envId=leetcode-75
- https://leetcode.com/problems/min-cost-climbing-stairs/?envType=study-plan-v2&envId=dynamic-programming
- https://leetcode.com/problems/determine-if-two-strings-are-close/?envType=study-plan-v2&envId=leetcode-75
- https://leetcode.com/problems/equal-row-and-column-pairs/?envType=study-plan-v2&envId=leetcode-75
- 후 다시 정신차리고 열심히 코테 준비하겠습니다
=> 2024-12-17 리트코드

장세훈/LeetCode/hard/SlidingWindowMaximum.java, 장세훈/LeetCode/medium/QueueReconstructionByHeight.java
- https://leetcode.com/problems/sliding-window-maximum/description/
- https://leetcode.com/problems/queue-reconstruction-by-height/description/
-
=> 2024-12-16-sh

장세훈/LeetCode/easy/AssignCookies.java, 장세훈/Programmers/Level2/소수찾기.java
- https://leetcode.com/problems/assign-cookies/
- https://school.programmers.co.kr/learn/courses/30/lessons/42839?language=java
-
=> 2024-12-17-sh

정수빈/LeetCode/medium/delete-and-earn.py, 정수빈/LeetCode/medium/house-robber.py
- https://leetcode.com/problems/house-robber/?envType=study-plan-v2&envId=dynamic-programming
- https://leetcode.com/problems/delete-and-earn/?envType=study-plan-v2&envId=dynamic-programming
- dp위주인데 뭔가 이해가 안가는.. 쉽지않습니다..
=> 2024-12-18 리트코드

장세훈/Programmers/Level1/폰켓몬.java, 장세훈/Programmers/Level2/전화번호목록.java
- https://school.programmers.co.kr/learn/courses/30/lessons/1845?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/42577
-
=> 2024-12-18-sh

정수빈/CodeTree/two-candies.py, 정수빈/CodeTree/two-candies_answer.py, 정수빈/LeetCode/medium/minimum-path-sum.py, 정수빈/LeetCode/medium/unique-paths2.py
- https://www.codetree.ai/training-field/frequent-problems/problems/two-candies/description?page=4&pageSize=20
- https://leetcode.com/problems/unique-paths/?envType=study-plan-v2&envId=dynamic-programming
- https://leetcode.com/problems/unique-paths/?envType=study-plan-v2&envId=dynamic-programming
- 엇 오타가 있네요 커밋 둘 다 오늘 풀었습니다. 19일!
- 코드트리 풀어봤는데, 진짜 2시간 내내 풀었는데, 시간오류났는데 막상 답을 보니까 별거 아니네요 ㅠㅠㅠ
=> 2024 12 19 sb

장세훈/Programmers/Level3/네트워크.java, 장세훈/Programmers/Level3/단어변환.java
- https://school.programmers.co.kr/learn/courses/30/lessons/43162
- https://school.programmers.co.kr/learn/courses/30/lessons/43163?language=java
- 프로그래머스 dfs 두문제 풀었습니다
=> 2024 12 19 sh

장세훈/Programmers/Level2/의상.java, 장세훈/Programmers/Level3/베스트앨범.java
- https://school.programmers.co.kr/learn/courses/30/lessons/42578?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/42579?language=java
- 프로그래머스 해시 문제
=> 2024-12-20-sh

정수빈/LeetCode/medium/maximal-square.py, 정수빈/LeetCode/medium/minimum-falling-path-sum.py, 정수빈/LeetCode/medium/unique-paths-ii.py, 정수빈/LeetCode/medium/word-break.py
- https://leetcode.com/problems/maximal-square/?envType=study-plan-v2&envId=dynamic-programming
- https://leetcode.com/problems/minimum-falling-path-sum/?envType=study-plan-v2&envId=dynamic-programming
- https://leetcode.com/problems/unique-paths-ii/?envType=study-plan-v2&envId=dynamic-programming
- https://leetcode.com/problems/word-break/submissions/1486078248/?envType=study-plan-v2&envId=dynamic-programming
-
=> 2024-12-23 리트코드

장세훈/Programmers/Level1/같은숫자는싫어.java, 장세훈/Programmers/Level2/기능개발.java, 장세훈/Programmers/Level2/올바른괄호.java, 장세훈/Programmers/Level2/프로세스.java
- https://school.programmers.co.kr/learn/courses/30/lessons/12906?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/42586
- https://school.programmers.co.kr/learn/courses/30/lessons/12909?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/42587?language=java
- 프로그래머스 스택/큐 문제
=> 2024-12-23-sh

장세훈/Programmers/Level2/큰수만들기.java, 장세훈/Programmers/Level3/가장먼노드.java
- https://school.programmers.co.kr/learn/courses/30/lessons/42883?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/49189?language=java
-
=> 2024-12-24-sh

정수빈/LeetCode/easy/binary-watch.py, 정수빈/LeetCode/hard/n-queens.py, 정수빈/LeetCode/medium/word-search.py
- https://leetcode.com/problems/binary-watch/?envType=problem-list-v2&envId=backtracking
- https://leetcode.com/problems/n-queens/?envType=problem-list-v2&envId=backtracking
- 백트래킹 대표적인 문제 n-queens 풀어봤습니다. 생각보다 괜찮게 풀려서 뿌듯하네여 그동안 성과가 좀 있는거 같아서요 
- 다들 연말 화이팅입니다!!
=> 2024-12-27 백트래킹 리트코드

정수빈/CodeTree/arrange-operator.py, 정수빈/CodeTree/autonomous-driving.py, 정수빈/CodeTree/firewall-installation.py, 정수빈/CodeTree/three-at-dawn-and-four-at-dusk.py
=> 2024-12-26 코드트리

장세훈/Programmers/Level2/다리를지나는트럭.java, 장세훈/Programmers/Level3/디스크컨트롤러.java
- https://school.programmers.co.kr/learn/courses/30/lessons/42583?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/42627?language=java
- 프로그래머스 2문제~
=> 2024-12-26-sh

장세훈/Programmers/Level1/모의고사.java, 장세훈/Programmers/Level1/최소직사각형.java, 장세훈/Programmers/Level2/카펫.java, 장세훈/Programmers/Level2/피로도.java
- https://school.programmers.co.kr/learn/courses/30/lessons/42840?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/86491?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/42842?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/87946?language=java
- 프로그래머스 완전 탐색 문제
=> 2024-12-30-sh

장세훈/Programmers/Level1/K번째수.java, 장세훈/Programmers/Level2/HIndex.java, 장세훈/Programmers/Level2/가장큰수.java
- https://school.programmers.co.kr/learn/courses/30/lessons/42748?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/42747?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/42746?language=java
- 프로그래머스 정렬 문제~
=> 2024-12-27-sh

정수빈/LeetCode/easy/add-binary.py, 정수빈/LeetCode/easy/add-digits.py, 정수빈/LeetCode/easy/fizz-buzz.py, 정수빈/LeetCode/medium/longest-increasing-subsequence.py
- https://leetcode.com/problems/add-binary/description/?envType=problem-list-v2&envId=simulation
- https://leetcode.com/problems/add-digits/?envType=problem-list-v2&envId=simulation
- https://leetcode.com/problems/fizz-buzz/editorial/?envType=problem-list-v2&envId=simulation
- 오늘은 쉬어가는 날입니다.. ㅎ
=> 2024-12-30 리트코드

오우영/Programmers/Level1/푸드파이터대회.js, 오우영/Programmers/Level2/이진변환반복하기.js
- [푸드파이터대회](https://school.programmers.co.kr/learn/courses/30/lessons/134240)
- [이진변환반복하기](https://school.programmers.co.kr/learn/courses/30/lessons/70129)
-
=> 2024-12-13 우영

장세훈/Programmers/Level2/모음사전.java, 장세훈/Programmers/Level2/전력망을둘로나누기.java
- https://school.programmers.co.kr/learn/courses/30/lessons/84512
- https://school.programmers.co.kr/learn/courses/30/lessons/86971?language=java
- 올해 마지막 날이네요
- 새해 복 많이 받으세요!
=> 2024-12-31-sh

정수빈/LeetCode/medium/combination-sum-iii.py, 정수빈/LeetCode/medium/rotting-oranges.py
- https://leetcode.com/problems/combination-sum-iii/description/?envType=study-plan-v2&envId=leetcode-75
- https://leetcode.com/problems/rotting-oranges/?envType=study-plan-v2&envId=leetcode-75
-
=> 2025-01-02 리트코드

장세훈/Programmers/Level1/체육복.java, 장세훈/Programmers/Level3/아이템줍기.java
- https://school.programmers.co.kr/learn/courses/30/lessons/42862?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/87694?language=java
-
=> 2025-01-01-sh

장세훈/Programmers/Level3/등굣길.java, 장세훈/Programmers/Level3/정수삼각형.java
- https://school.programmers.co.kr/learn/courses/30/lessons/42898?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/43105
-
=> 2025-01-03-sh

정수빈/LeetCode/medium/max-consecutive-ones-iii.py, 정수빈/LeetCode/medium/max-number-of-k-sum-pairs.py
- https://leetcode.com/problems/max-number-of-k-sum-pairs/description/?envType=study-plan-v2&envId=leetcode-75
- https://leetcode.com/problems/max-consecutive-ones-iii/?envType=study-plan-v2&envId=leetcode-75
- 1월 4일에 푼 걸 3일에 푼 척 (머쓱)
=> 2025-01-03 리트코드

장세훈/Programmers/Level2/JadenCase.java, 장세훈/Programmers/Level2/숫자의표현.java, 장세훈/Programmers/Level2/이진변환반복하기.java, 장세훈/Programmers/Level2/최솟값만들기.java, 장세훈/Programmers/Level2/피보나치수.java
- https://school.programmers.co.kr/learn/courses/30/lessons/12951
- https://school.programmers.co.kr/learn/courses/30/lessons/70129
- https://school.programmers.co.kr/learn/courses/30/lessons/12924
- https://school.programmers.co.kr/learn/courses/30/lessons/12945
- https://school.programmers.co.kr/learn/courses/30/lessons/12941
- 프로그래머스 2,3 레벨 쉬운순으로 정렬해서 풀어보겠습니다~
=> 2025-01-06-sh

정수빈/LeetCode/easy/valid-palindrome-ii.py, 정수빈/LeetCode/easy/valid-word-abbreviation.py
- https://leetcode.com/problems/valid-word-abbreviation/description/
- https://leetcode.com/problems/valid-palindrome-ii/description/
-
=> 2025-01-06 리트코드

정수빈/LeetCode/medium/longest-subarray-of-1s-after-deleting-one-element.py
- https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/description/?envType=study-plan-v2&envId=leetcode-75
- 한문제만 풀었습니다..ㅎ 밀렸네여 ㅠㅠ
=> 2025-01-04 리트코드

곽경진/Programmers/Level2/다리를_지나는_트럭.java, 곽경진/Programmers/Level2/주식가격.java
- [다리를_지나는_트럭](https://school.programmers.co.kr/learn/courses/30/lessons/42583)
- [주식가격](https://school.programmers.co.kr/learn/courses/30/lessons/42584)
-
=> 2024-12-11

곽경진/Programmers/Level2/jadenCase_문자열만들기.java, 곽경진/Programmers/Level2/뒤에_있는_큰_수_찾기.java
- [뒤에_있는_큰_수_찾기](https://school.programmers.co.kr/learn/courses/30/lessons/154539)
- [jadenCase_문자열만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12951)
-
=> 2024-12-13

오우영/Programmers/Level2/영어끝말잇기.js, 오우영/Programmers/Level2/예상대진표.js
- [예상대진표](https://school.programmers.co.kr/learn/courses/30/lessons/12985)
- [영어끝말잇기](https://school.programmers.co.kr/learn/courses/30/lessons/12981)
-
=> 영어끝말잇기, 예상대진표

장세훈/Programmers/Level2/구명보트.java, 장세훈/Programmers/Level2/멀리뛰기.java, 장세훈/Programmers/Level2/영어끝말잇기.java, 장세훈/Programmers/Level2/짝지어제거하기.java
- https://school.programmers.co.kr/learn/courses/30/lessons/12981
- https://school.programmers.co.kr/learn/courses/30/lessons/12914
- https://school.programmers.co.kr/learn/courses/30/lessons/42885
- https://school.programmers.co.kr/learn/courses/30/lessons/12973
-
=> 2025-01-07-sh

정수빈/LeetCode/easy/counting-bits.py, 정수빈/LeetCode/easy/single-number.py, 정수빈/LeetCode/medium/design-sql.py, 정수빈/LeetCode/medium/merge-operations-to-turn-array-into-a-palindrome.py, 정수빈/LeetCode/medium/minimum-number-of-keypresses.py, 정수빈/LeetCode/medium/valid-palindrome-iv.py
- https://leetcode.com/problems/counting-bits/description/?envType=study-plan-v2&envId=leetcode-75
- https://leetcode.com/problems/single-number/description/?envType=study-plan-v2&envId=leetcode-75
- https://leetcode.com/problems/design-sql/description/?envType=study-plan-v2&envId=amazon-spring-23-high-frequency
- 8일차꺼 미리 올립니다 (머쓱)
=> 2025-01-08 리트코드

정수빈/LeetCode/easy/valid-palindrome-ii.py, 정수빈/LeetCode/medium/optimal-partition-of-string.py, 정수빈/LeetCode/medium/the-kth-factor-of-n.py
- https://leetcode.com/problems/optimal-partition-of-string/description/?envType=study-plan-v2&envId=amazon-spring-23-high-frequency
- https://leetcode.com/problems/the-kth-factor-of-n/description/?envType=study-plan-v2&envId=amazon-spring-23-high-frequency
- 세훈님 남은 저희끼리 열심히 해봅시당!!
=> 2025-01-07 리트코드

장세훈/Programmers/Level2/n2배열자르기.java, 장세훈/Programmers/Level2/예상대진표.java, 장세훈/Programmers/Level2/점프와순간이동.java, 장세훈/Programmers/Level2/할인행사.java
- https://school.programmers.co.kr/learn/courses/30/lessons/87390
- https://school.programmers.co.kr/learn/courses/30/lessons/12985
- https://school.programmers.co.kr/learn/courses/30/lessons/12980
- https://school.programmers.co.kr/learn/courses/30/lessons/131127
- 정답률 60%대 부터는 생각좀 하면서 풀어야 되네요 ㅋㅋ
=> 2025-01-08-sh

장세훈/Programmers/Level2/N개의최소공배수.java, 장세훈/Programmers/Level2/뉴스클러스터링.java, 장세훈/Programmers/Level2/방문길이.java, 장세훈/Programmers/Level2/튜플.java, 장세훈/Programmers/Level2/행렬의곱셈.java
- https://school.programmers.co.kr/learn/courses/30/lessons/17677
- https://school.programmers.co.kr/learn/courses/30/lessons/64065
- https://school.programmers.co.kr/learn/courses/30/lessons/12949
- https://school.programmers.co.kr/learn/courses/30/lessons/49994
- https://school.programmers.co.kr/learn/courses/30/lessons/12953
-
=> 2025-01-09-sh

정수빈/LeetCode/medium/largest-number.py, 정수빈/LeetCode/medium/meeting-rooms-ii.py
- https://leetcode.com/problems/largest-number/description/?envType=problem-list-v2&envId=greedy
- https://leetcode.com/problems/meeting-rooms-ii/description/?envType=problem-list-v2&envId=greedy
- greedy 유형위주로 해보려고 하는데, 이것도 먼가 좀 어렵네요 ㅋㅋㅋ
=> 2025-01-09 리트코드

장세훈/Programmers/Level2/뒤에있는큰수찾기.java, 장세훈/Programmers/Level2/땅따먹기.java, 장세훈/Programmers/Level2/스킬트리.java, 장세훈/Programmers/Level2/택배상자.java
- https://school.programmers.co.kr/learn/courses/30/lessons/131704
- https://school.programmers.co.kr/learn/courses/30/lessons/49993
- https://school.programmers.co.kr/learn/courses/30/lessons/12913
- https://school.programmers.co.kr/learn/courses/30/lessons/154539
-
=> 2025-01-11-sh

장세훈/Programmers/Level2/k진수에서소수개수구하기.java, 장세훈/Programmers/Level2/n진수게임.java, 장세훈/Programmers/Level2/롤케이크자르기.java, 장세훈/Programmers/Level2/삼차압축.java
- https://school.programmers.co.kr/learn/courses/30/lessons/92335
- https://school.programmers.co.kr/learn/courses/30/lessons/17687
- https://school.programmers.co.kr/learn/courses/30/lessons/17684
- https://school.programmers.co.kr/learn/courses/30/lessons/132265?language=java
-
=> 2025-01-10-sh

정수빈/LeetCode/easy/two-sum-iv-input-is-a-bst.py, 정수빈/LeetCode/medium/number-of-distinct-islands.py
- https://leetcode.com/problems/two-sum-iv-input-is-a-bst/description/?envType=problem-list-v2&envId=breadth-first-search
- https://leetcode.com/problems/number-of-distinct-islands/description/?envType=problem-list-v2&envId=breadth-first-search
- 저도 세훈님께 자극받아서 주말분 올립니다 ㅎㅎ
=> 2025-01-11 리트코드

정수빈/LeetCode/medium/reorganize-string.py, 정수빈/LeetCode/medium/word-subsets.py
- https://leetcode.com/problems/word-subsets/description/?envType=daily-question&envId=2025-01-10
- https://leetcode.com/problems/reorganize-string/description/?envType=problem-list-v2&envId=greedy
-
=> 2025-01-10 리트코드

정수빈/LeetCode/easy/remove-duplicates-from-sorted-list.py, 정수빈/LeetCode/easy/reverse-string.py, 정수빈/LeetCode/easy/substring-matching-pattern.py
- https://leetcode.com/problems/reverse-string/description/?envType=company&envId=apple&favoriteSlug=apple-three-months
- https://leetcode.com/problems/substring-matching-pattern/
- 쉬운문제풀었슴다 ㅋㅋㅋ 
- 수요일에 면접인데 그거 때문에 며칠 좀 소홀해질지도요! ㅠ
=> 2025-01-13 리트코드

장세훈/Programmers/Level2/숫자변환하기.java, 장세훈/Programmers/Level2/주차요금계산.java, 장세훈/Programmers/Level3/숫자게임.java, 장세훈/Programmers/Level3/야근지수.java, 장세훈/Programmers/Level3/최고의집합.java
- https://school.programmers.co.kr/learn/courses/30/lessons/92341
- https://school.programmers.co.kr/learn/courses/30/lessons/154538
- https://school.programmers.co.kr/learn/courses/30/lessons/12987
- https://school.programmers.co.kr/learn/courses/30/lessons/12938
- https://school.programmers.co.kr/learn/courses/30/lessons/12927
-
=> 2025-01-13-sh

장세훈/Programmers/Level2/아xn타일링.java, 장세훈/Programmers/Level2/오픈채팅방.java, 장세훈/Programmers/Level3/단속카메라.java
- https://school.programmers.co.kr/learn/courses/30/lessons/12900
- https://school.programmers.co.kr/learn/courses/30/lessons/42888
- https://school.programmers.co.kr/learn/courses/30/lessons/42884
-
=> 2025-01-14-sh

장세훈/Programmers/Level2/다른비트.java, 장세훈/Programmers/Level2/쿼드압축후개수세기.java
- https://school.programmers.co.kr/learn/courses/30/lessons/77885
- https://school.programmers.co.kr/learn/courses/30/lessons/68936
-
=> 2025-01-15-sh

장세훈/Programmers/Level2/마법의엘리베이터.java, 장세훈/Programmers/Level2/연속된부분수열의합.java
- https://school.programmers.co.kr/learn/courses/30/lessons/148653
- https://school.programmers.co.kr/learn/courses/30/lessons/178870/solution_groups?language=java
-
=> 2025-01-17-sh

장세훈/Programmers/Level2/두큐합같게만들기.java, 장세훈/Programmers/Level2/삼각달팽이.java
- https://school.programmers.co.kr/learn/courses/30/lessons/118667
- https://school.programmers.co.kr/learn/courses/30/lessons/68645
-
=> 2025-01-16-sh

정수빈/LeetCode/medium/decode-string.py, 정수빈/LeetCode/medium/delete-the-middle-node-of-a-linked-list.py, 정수빈/LeetCode/medium/evaluate-reverse-polish-notation.py, 정수빈/LeetCode/medium/insert-interval.py, 정수빈/LeetCode/medium/leaf-similar-trees.py, 정수빈/LeetCode/medium/make-lexicographically-smallest-array-by-swapping-elements.py, 정수빈/LeetCode/medium/maximum-twin-sum-of-a-linked-list.py, 정수빈/LeetCode/medium/min-stack.py, 정수빈/LeetCode/medium/minimum-remove-to-make-valid-parentheses.py, 정수빈/LeetCode/medium/nearest-exit-from-entrance-in-maze.py, 정수빈/LeetCode/medium/odd-even-linked-list.py
- https://leetcode.com/problems/insert-interval/description/?envType=study-plan-v2&envId=top-interview-150
- https://leetcode.com/problems/make-lexicographically-smallest-array-by-swapping-elements/description/
- 흑흑 답지만 많이 봤네요
=> 2025-01-27 리트코드

정수빈/LeetCode/easy/maximum-ascending-subarray-sum.py, 정수빈/LeetCode/medium/nested-list-weight-sum.py, 정수빈/LeetCode/medium/string-compression-iii.py, 정수빈/LeetCode/medium/walking-robot-simulation.py
- https://leetcode.com/problems/maximum-ascending-subarray-sum/description/?envType=daily-question&envId=2025-02-04
- https://leetcode.com/problems/nested-list-weight-sum/
- https://leetcode.com/problems/string-compression-iii/
-
=> 2025-02-04 리트코드

정수빈/LeetCode/easy/longest-strictly-increasing-or-strictly-decreasing-subarray.py, 정수빈/LeetCode/medium/basic-calculator-ii.py, 정수빈/LeetCode/medium/lowest-common-ancestor-of-a-binary-tree-iii.py
- https://leetcode.com/problems/longest-strictly-increasing-or-strictly-decreasing-subarray/description/?envType=daily-question&envId=2025-02-03
- https://leetcode.com/problems/basic-calculator-ii/
- fork 해서 했는데, 먼가 더 귀찮은거 같아서 다시 main 에 직접 브랜치따서 합니다 ㅋㅋ
=> 2025-02-03 리트코드

장세훈/Programmers/Level2/미로탈출.java, 장세훈/Programmers/Level2/숫자카드나누기.java
- https://school.programmers.co.kr/learn/courses/30/lessons/159993?language=java
- https://school.programmers.co.kr/learn/courses/30/lessons/135807?language=java
- 오랜만이군요 ㅋㅋ 다시 열심히 하겠습니당
=> 2025-02-04-sh

정수빈/LeetCode/easy/toeplitz-matrix.py, 정수빈/LeetCode/hard/minimum-cost-to-hire-k-workers.py, 정수빈/LeetCode/medium/bulls-and-cows.py
- https://leetcode.com/problems/toeplitz-matrix/description/
- https://leetcode.com/problems/toeplitz-matrix/
- https://leetcode.com/problems/bulls-and-cows/description/
-
=> 2025-02-05 리트코드 (미리 올립니다 ㅎ)

장세훈/Programmers/Level2/가장큰정사각형찾기.java, 장세훈/Programmers/Level2/메뉴리뉴얼.java
- https://school.programmers.co.kr/learn/courses/30/lessons/12905
- https://school.programmers.co.kr/learn/courses/30/lessons/72411
-
=> 2025-02-05-sh

정수빈/LeetCode/medium/divide-two-integers.py, 정수빈/LeetCode/medium/next-permutation.py, 정수빈/LeetCode/medium/remove-nth-node-from-end-of-list.py, 정수빈/LeetCode/medium/search-in-rotated-sorted-array.py, 정수빈/LeetCode/medium/swap-nodes-in-pairs.py
- https://leetcode.com/problems/divide-two-integers/
- https://leetcode.com/problems/next-permutation/description/
- https://leetcode.com/problems/remove-nth-node-from-end-of-list/
- https://leetcode.com/problems/search-in-rotated-sorted-array/
- https://leetcode.com/problems/swap-nodes-in-pairs/
- 다들 화이팅입니닷!!
=> 2025-02-06 리트코드

최서영/LeetCode/easy/LengthofLastWord.ts, 최서영/LeetCode/easy/PalindromeNumber.ts, 최서영/LeetCode/easy/SameTree.ts
- [https://leetcode.com/problems/length-of-last-word/](https://leetcode.com/problems/length-of-last-word/)
- [https://leetcode.com/problems/palindrome-number/](https://leetcode.com/problems/palindrome-number/)
- [https://leetcode.com/problems/same-tree/](https://leetcode.com/problems/same-tree/)
- 오늘 오전 / 저녁 일정때문에 이지이지이지 (3문제) 풀었습니다 ⚲_⚲
- 낼은 미디움에 도전!!!
=> 2025-02-06-sy Leetcode

장세훈/Programmers/Level2/스티커모으기2.java, 장세훈/Programmers/Level3/가장긴팰린드롬.java
- https://school.programmers.co.kr/learn/courses/30/lessons/12904
- https://school.programmers.co.kr/learn/courses/30/lessons/12971
- 정답률 50%대에서 막히기 시작하네요 ㅠㅠ ㅋㅋ
=> 2025-02-06-sh

정수빈/LeetCode/easy/coin-change.py, 정수빈/LeetCode/easy/find-the-difference.py, 정수빈/LeetCode/easy/merge-strings-alternately.py, 정수빈/LeetCode/easy/repeated-substring-pattern.py, 정수빈/LeetCode/easy/sign-of-the-product-of-an-array.py, 정수빈/LeetCode/medium/dot-product-of-two-sparse-vectors.py, 정수빈/LeetCode/medium/lexicographical-numbers.py, 정수빈/LeetCode/medium/lowest-common-ancestor-of-a-binary-tree.py, 정수빈/LeetCode/medium/shortest-path-in-binary-matrix.py, 정수빈/LeetCode/medium/swap-nodes-in-pairs.py, 정수빈/LeetCode/medium/tuple-with-same-product.py
- https://leetcode.com/problems/tuple-with-same-produc
- https://leetcode.com/problems/coin-change/
- https://leetcode.com/problems/find-the-difference
- https://leetcode.com/problems/merge-strings-alternately/
- https://leetcode.com/problems/sign-of-the-product-of-an-array
- https://leetcode.com/problems/dot-product-of-two-sparse-vectors/
- https://leetcode.com/problems/lexicographical-numbers/description/?envType=problem-list-v2&envId=depth-first-search
- 등등 
- 먼가 풀다보니 많이 풀게됐네여 ㅋㅋ
=> 2025-02-07 리트코드

장세훈/Programmers/Level2/멀쩡한사각형.java, 장세훈/Programmers/Level2/문자열압축.java
- https://school.programmers.co.kr/learn/courses/30/lessons/62048
- https://school.programmers.co.kr/learn/courses/30/lessons/60057
- 한 주간 수고하셨습니다~
=> 2025-02-07-sh

정수빈/LeetCode/medium/graph-valid-tree.py, 정수빈/LeetCode/medium/shortest-bridge.py
- https://leetcode.com/problems/graph-valid-tree/
- https://leetcode.com/problems/shortest-bridge/description/?envType=problem-list-v2&envId=depth-first-search
-
=> 2025-02-08 리트코드

장세훈/Programmers/Level3/불량사용자.java
- https://school.programmers.co.kr/learn/courses/30/lessons/64064
- 한 문제 풀었습니다. ㅜㅜ 점점 안풀리기 시작하네요 ㅋㅋ
=> 2025-02-10-sh

정수빈/LeetCode/easy/balanced-binary-tree.py, 정수빈/LeetCode/easy/binary-tree-postorder-traversal.py, 정수빈/LeetCode/easy/binary-tree-preorder-traversal.py, 정수빈/LeetCode/easy/minimum-depth-of-binary-tree.py, 정수빈/LeetCode/easy/range-sum-of-bst.py, 정수빈/LeetCode/medium/binary-tree-upside-down.py, 정수빈/LeetCode/medium/path-sum-ii.py
- https://leetcode.com/problems/path-sum-ii/?envType=problem-list-v2&envId=depth-first-search
- https://leetcode.com/problems/balanced-binary-tree
- https://leetcode.com/problems/binary-tree-postorder-traversal/?envType=problem-list-v2&envId=depth-first-search
- https://leetcode.com/problems/binary-tree-preorder-traversal/description/?envType=problem-list-v2&envId=depth-first-search
- https://leetcode.com/problems/minimum-depth-of-binary-tree
- 주말에 한거랑 같이해서 올립니다!
=> 2025-02-10 리트코드

정수빈/LeetCode/medium/combination-sum-ii.py, 정수빈/LeetCode/medium/count-and-say.py, 정수빈/LeetCode/medium/multiply-strings.py, 정수빈/LeetCode/medium/sort-colors.py, 정수빈/Programmers/Level2/프렌즈4블록.py
- https://leetcode.com/problems/combination-sum-ii/
- https://leetcode.com/problems/count-and-say/
- https://leetcode.com/problems/multiply-strings/
- https://leetcode.com/problems/sort-colors.py
- https://school.programmers.co.kr/learn/courses/30/lessons/17679?language=python3
- 다들 화이팅입니닷
- 저도 먼가 자극받아서 세훈님이 푸신 카카오 프렌즈 문제 풀었는데, 세훈님거가 제거보다 훨씬 효율적으로 푼거같아요 ㅋㅋㅋ
=> 2025-02-12 리트코드

정수빈/LeetCode/medium/jump-game-ii.py, 정수빈/LeetCode/medium/rotate-list.py
- https://leetcode.com/problems/jump-game-ii
- https://leetcode.com/problems/rotate-list/
- 이번에 푼 문제들의 해답은 좀 와! 기발하다 싶은 느낌을 주는 문제였습니다. 제가 푼건 On2인데 답지는 0n라던가.. 정말 코테의세곈 어렵습니다..
=> 2025-02-13 리트코드

정수빈/LeetCode/easy/pascals-triangle.py, 정수빈/LeetCode/medium/partition-list.py
- https://leetcode.com/problems/pascals-triangle/
- https://leetcode.com/problems/partition-list/
- 오늘은 짤막하게 했습니다 ㅎㅎ
=> 2025-02-14 리트코드

장세훈/Programmers/Level2/거리두기확인하기.java, 장세훈/Programmers/Level2/테이블해시함수.java
- https://school.programmers.co.kr/learn/courses/30/lessons/81302
- https://school.programmers.co.kr/learn/courses/30/lessons/147354
- 어제 카페에서 알고리즘하다가 제 맥북에 커피를 쏟는 바람에 못했었네요. ;;
- 자판을 누를때마다 커피가 나오면서 간헐적으로 입력이 안되더군요 ㅋㅋ
- 다행히 애플케어플러스가 있어서 수리는 가능합니다. 맥북은 리퍼가 안되어서 애플케어플러스가 없으면 그냥 새거 사라고 조언해주네요
=> 2025-02-14-sh

정수빈/LeetCode/easy/missing-number.py, 정수빈/LeetCode/easy/missing-ranges.py, 정수빈/LeetCode/easy/number-of-1-bits.py, 정수빈/LeetCode/medium/decode-ways.py, 정수빈/LeetCode/medium/letter-tile-possibilities.py
- https://leetcode.com/problems/missing-number/
- https://leetcode.com/problems/decode-ways/
- 간단한 문제 푼거 올립니다 ~
=> 2025-02-16 리트코드

장세훈/Programmers/Level2/디펜스게임.java, 장세훈/Programmers/Level2/리코쳇로봇.java
- https://school.programmers.co.kr/learn/courses/30/lessons/142085
- https://school.programmers.co.kr/learn/courses/30/lessons/169199
-
=> 2025-02-17-sh

정수빈/LeetCode/medium/best-sightseeing-pair.py, 정수빈/LeetCode/medium/construct-smallest-number-from-di-string.py, 정수빈/LeetCode/medium/subsets-ii.py, 정수빈/LeetCode/medium/subsets.py
- https://leetcode.com/problems/best-sightseeing-pair/
- https://leetcode.com/problems/construct-smallest-number-from-di-string
- https://leetcode.com/problems/subsets-ii/
- https://leetcode.com/problems/subsets/
- 
- 가끔 리트코드에 데일리 문제 푸는데 (오늘 새로 추가된 문제), 이거 한번 풀면 살짝 뿌듯하네요
=> 2025-02-18 리트코드

장세훈/Programmers/Level2/서버증설횟수.java, 장세훈/Programmers/Level3/연속펄스부분수열의합.java
- https://school.programmers.co.kr/learn/courses/30/lessons/389479
- https://school.programmers.co.kr/learn/courses/30/lessons/161988
- 문제 풀면서 랭킹 오르는 재미도 있었는데, 이제 랭킹이 잘 안오르네요 ㅋㅋ
=> 2025-02-18-sh

정수빈/LeetCode/easy/minimum-string-length-after-removing-substrings.py, 정수빈/LeetCode/hard/first-missing-positive.py, 정수빈/LeetCode/medium/break-a-palindrome.py, 정수빈/LeetCode/medium/find-the-student-that-will-replace-the-chalk.py, 정수빈/LeetCode/medium/find-unique-binary-string.py, 정수빈/LeetCode/medium/spiral-matrix-iv.py
- https://leetcode.com/problems/spiral-matrix-iv/
- https://leetcode.com/problems/minimum-string-length-after-removing-substrings/
- https://leetcode.com/problems/first-missing-positive
- https://leetcode.com/problems/break-a-palindrome/
- https://leetcode.com/problems/find-the-student-that-will-replace-the-chalk/
- https://leetcode.com/problems/find-unique-binary-string
- 어제분이랑 같이 올립니다!
=> 2025-02-20 리트코드

장세훈/Programmers/Level2/점찍기.java, 장세훈/Programmers/Level2/줄서는방법.java
- https://school.programmers.co.kr/learn/courses/30/lessons/140107
- https://school.programmers.co.kr/learn/courses/30/lessons/12936
- 쉬운 문제인줄 알고 덤볐으나 결국 다 못풀었네요. 이런 수학적 접근을 어떻게 하는건지..ㄷㄷ
=> 2025-02-20-sh

정수빈/LeetCode/medium/factor-combinations.py, 정수빈/LeetCode/medium/find-elements-in-a-contaminated-binary-tree.py, 정수빈/LeetCode/medium/permutations-ii.py
- https://leetcode.com/problems/factor-combinations
- https://leetcode.com/problems/find-elements-in-a-contaminated-binary-tree/
- https://leetcode.com/problems/permutations-ii
- 오늘도 화이팅!!
=> 2025-02-21 리트코드

장세훈/LeetCode/medium/BrowserHistory.java, 장세훈/LeetCode/medium/SmallestDivisor.java
- https://leetcode.com/problems/design-browser-history/
- https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/
- 리트코드 오랜만에 풀어봤습니다~ 문제가 간결해서 좋네요 ㅎㅎ
=> 2025-02-21-sh

정수빈/LeetCode/easy/contains-duplicate.py, 정수빈/LeetCode/easy/shortest-word-distance.py, 정수빈/LeetCode/hard/permutation-sequence.py
- https://leetcode.com/problems/contains-duplicate/
- https://leetcode.com/problems/shortest-word-distance/
- https://leetcode.com/problems/permutation-sequence
-
=> 2025-02-24 리트코드

장세훈/LeetCode/easy/RomanToInteger.java, 장세훈/LeetCode/medium/RemoveNthFromEnd.java
- https://leetcode.com/problems/roman-to-integer/submissions/1553773756/
- https://leetcode.com/problems/remove-nth-node-from-end-of-list/
-
=> 2025-02-24-sh

정수빈/LeetCode/easy/check-if-array-is-good.py, 정수빈/LeetCode/easy/check-if-digits-are-equal-in-string-after-operations-i.py, 정수빈/LeetCode/easy/confusing-number.py, 정수빈/LeetCode/easy/count-pairs-that-form-a-complete-day-i.py, 정수빈/LeetCode/easy/minimum-number-game.py, 정수빈/LeetCode/easy/sum-of-good-numbers.py
- https://leetcode.com/problems/check-if-array-is-good/
- https://leetcode.com/problems/check-if-digits-are-equal-in-string-after-operations-i/
- https://leetcode.com/problems/confusing-number/
- https://leetcode.com/problems/count-pairs-that-form-a-complete-day-i/
- https://leetcode.com/problems/minimum-number-game/
- https://leetcode.com/problems/sum-of-good-numbers/
- 오늘도 하기싫어서 easy로 물량으로 밀어부쳤습니다 ㅋㅋㅋ 왜캐 요새 하기싫을까여
=> 2025-02-25 리트코드

장세훈/LeetCode/medium/NumPairsDivisibleBy60.java, 장세훈/LeetCode/medium/WordDictionary.java
- https://leetcode.com/problems/design-add-and-search-words-data-structure
- https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/
-
=> 2025-02-26-sh

장세훈/LeetCode/medium/FindingUsersActiveMinutes.java, 장세훈/LeetCode/medium/IsValidSudoku.java
- https://leetcode.com/problems/finding-the-users-active-minutes/
- https://leetcode.com/problems/valid-sudoku/
-
=> 2025-02-25-sh

정수빈/LeetCode/easy/clear-digits.py, 정수빈/LeetCode/medium/length-of-longest-fibonacci-subsequence.py
- https://leetcode.com/problems/clear-digits/
- https://leetcode.com/problems/length-of-longest-fibonacci-subsequence/
-
=> 2025-02-76 리트코드

장세훈/LeetCode/medium/InsertInterval.java, 장세훈/LeetCode/medium/UniquePaths.java
- https://leetcode.com/problems/unique-paths/
- https://leetcode.com/problems/insert-interval/
-
=> 2025-02-27-sh

정수빈/LeetCode/easy/excel-sheet-column-title.py, 정수빈/LeetCode/medium/maximum-absolute-sum-of-any-subarray.py, 정수빈/LeetCode/medium/maximum-subarray.py
- https://leetcode.com/problems/excel-sheet-column-title/
- https://leetcode.com/problems/maximum-absolute-sum-of-any-subarray
- https://leetcode.com/problems/maximum-subarray/
- 카데인 알고리즘 제대로 알고갑니다 ㅎㅎ
=> 2025-02-28 리트코드

최서영/LeetCode/medium/LengthOfLongestSubstring.ts, 최서영/LeetCode/medium/LongestPalindrome.ts
- [Longest Substring Without Repeating Characters](https://leetcode.com/problems/longest-substring-without-repeating-characters/)
- [Longest Palindromic Substring](https://leetcode.com/problems/longest-palindromic-substring/)
- 정말 오랜만에 올리는군요! ⚲_⚲
- 최근 상태가 좋지 않아서 어딘가 집중하고 싶어서 2문제를 풀었는데 아직 너무 어렵습니다
- 꾸준히 올려볼게요!!!
- 3월도 홧팅홧팅
=> 2025-03-01 SY leetcode(medium)

정수빈/LeetCode/medium/design-hit-counter.py, 정수빈/LeetCode/medium/koko-eating-bananas.py
- https://leetcode.com/problems/design-hit-counter/
- https://leetcode.com/problems/koko-eating-bananas
- 3월 4일꺼 미리 풀어서 올립니다 ㅎ..
=> 2025-03-04 리트코드

장세훈/LeetCode/medium/Rob.java, 장세훈/LeetCode/medium/WordSearch.java
- https://leetcode.com/problems/house-robber/
- https://leetcode.com/problems/word-search/
-
=> 2025-02-28-sh

장세훈/LeetCode/medium/NumDecodings.java, 장세훈/LeetCode/medium/SimplifyPath.java
- https://leetcode.com/problems/decode-ways/description/
- https://leetcode.com/problems/simplify-path/
- 악 벌써 3월이네요. 3월도 화이팅입니다.
=> 2025-03-03-sh

장세훈/LeetCode/hard/TrappingRainWater.java, 장세훈/LeetCode/medium/BinaryTreeLevelOrderTraversal.java, 장세훈/LeetCode/medium/LongestIncreasingSubsequence.java, 장세훈/LeetCode/medium/SetMatrixZeroes.java
- https://leetcode.com/problems/binary-tree-level-order-traversal/
- https://leetcode.com/problems/set-matrix-zeroes/
-
=> 2025-03-04-sh

정수빈/LeetCode/easy/apply-operations-to-an-array.py, 정수빈/LeetCode/medium/check-if-number-is-a-sum-of-powers-of-three.py
- https://leetcode.com/problems/apply-operations-to-an-array
- https://leetcode.com/problems/check-if-number-is-a-sum-of-powers-of-three/
- 미리 올립니다 ㅋㅋ
=> 2025-03-05 리트코드

장세훈/LeetCode/hard/TrappingRainWater.java, 장세훈/LeetCode/medium/LongestIncreasingSubsequence.java
- https://leetcode.com/problems/trapping-rain-water/
- https://leetcode.com/problems/longest-increasing-subsequence/
- 아 main에 바로 푸시를 해버렸네요 ;;
=> 2025-03-05-sh

정수빈/LeetCode/medium/count-total-number-of-colored-cells.py, 정수빈/LeetCode/medium/longest-substring-with-at-most-two-distinct-characters.py
- https://leetcode.com/problems/count-total-number-of-colored-cells/
- https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/
- 3월인데 춥네요 ㅠㅠ 다들 감기조심하세여!
=> 2025-03-06 리트코드

장세훈/LeetCode/easy/FindIfPathExistsInGraph.java, 장세훈/LeetCode/medium/JumpGame2.java
- https://leetcode.com/problems/find-if-path-exists-in-graph/
- https://leetcode.com/problems/jump-game-ii/
- 음 그래프문제 오랜만에 풀어보니 또 낯서네요. 그래서 일단 쉬운걸로.. ㅋㅋ
=> 2025-03-06-sh

정수빈/LeetCode/easy/minimum-recolors-to-get-k-consecutive-black-blocks.py, 정수빈/LeetCode/easy/rank-transform-of-an-array.py
- https://leetcode.com/problems/minimum-recolors-to-get-k-consecutive-black-blocks
- https://leetcode.com/problems/rank-transform-of-an-array/
- 오늘도 화이팅입니닷!
=> 2025-03-11 리트코드

장세훈/LeetCode/medium/PivotIndex.java, 장세훈/LeetCode/medium/ProductOfNumbers.java
- https://leetcode.com/problems/find-pivot-index/
- https://leetcode.com/problems/product-of-the-last-k-numbers/
- 누적곲이란 개념을 알게되었네요!
=> 2025-03-11-sh

정수빈/LeetCode/easy/merge-two-2d-arrays-by-summing-values.py, 정수빈/LeetCode/medium/product-of-the-last-k-numbers.py
- https://leetcode.com/problems/merge-two-2d-arrays-by-summing-values
- https://leetcode.com/problems/product-of-the-last-k-numbers/
- 누적곱 저도 풀어봤는데, 역시 아이디어가 중요한거 같습니다 ㅋㅋㅋ
=> 2025-03-13 리트코드
